version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: node_modules/.bin/nodemon --exec npm start
    tty: true
    environment:
      NODE_ENV: dev
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - mongodb
  mongodb:
    image: mongo